### ISSUE TITLE
Diseñar logo de boty

### ISSUE THREAD

**Issue by Andresggomez** [Andresggomez/boty#17]

**Comment by AldahirRojas** [comment]
![Diseño sin título (2)](https://user-images.githubusercontent.com/54284797/160202319-8b0c427a-9db7-42d0-8f9f-64090c0e1c81.png)

**Comment by AldahirRojas** [comment]
![Diseño sin título (3)](https://user-images.githubusercontent.com/54284797/160207428-f5ceaac3-21ee-44fe-a316-5198b2290836.png)

**Comment by AldahirRojas** [comment]
Se diseño el logo de Boty

**Comment by AldahirRojas** [comment]
Se diseño el logo de Boty
